/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PloegenRouteImport } from './routes/ploegen'
import { Route as PloegenIndexRouteImport } from './routes/ploegen.index'
import { Route as PloegenSlugRouteImport } from './routes/ploegen.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PloegenRoute = PloegenRouteImport.update({
  id: '/ploegen',
  path: '/ploegen',
  getParentRoute: () => rootRouteImport,
} as any)
const PloegenIndexRoute = PloegenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PloegenRoute,
} as any)
const PloegenSlugRoute = PloegenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PloegenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ploegen': typeof PloegenRouteWithChildren
  '/ploegen/$slug': typeof PloegenSlugRoute
  '/ploegen/': typeof PloegenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ploegen/$slug': typeof PloegenSlugRoute
  '/ploegen': typeof PloegenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ploegen': typeof PloegenRouteWithChildren
  '/ploegen/$slug': typeof PloegenSlugRoute
  '/ploegen/': typeof PloegenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ploegen' | '/ploegen/$slug' | '/ploegen/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ploegen/$slug' | '/ploegen'
  id: '__root__' | '/' | '/ploegen' | '/ploegen/$slug' | '/ploegen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PloegenRoute: typeof PloegenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ploegen': {
      id: '/ploegen'
      path: '/ploegen'
      fullPath: '/ploegen'
      preLoaderRoute: typeof PloegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ploegen/': {
      id: '/ploegen/'
      path: '/'
      fullPath: '/ploegen/'
      preLoaderRoute: typeof PloegenIndexRouteImport
      parentRoute: typeof PloegenRoute
    }
    '/ploegen/$slug': {
      id: '/ploegen/$slug'
      path: '/$slug'
      fullPath: '/ploegen/$slug'
      preLoaderRoute: typeof PloegenSlugRouteImport
      parentRoute: typeof PloegenRoute
    }
  }
}

interface PloegenRouteChildren {
  PloegenSlugRoute: typeof PloegenSlugRoute
  PloegenIndexRoute: typeof PloegenIndexRoute
}

const PloegenRouteChildren: PloegenRouteChildren = {
  PloegenSlugRoute: PloegenSlugRoute,
  PloegenIndexRoute: PloegenIndexRoute,
}

const PloegenRouteWithChildren =
  PloegenRoute._addFileChildren(PloegenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PloegenRoute: PloegenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
